"input" is reserved.
RuntimeError: error: 2: name 'input' is reserved
uniform shader input;
               ^^^^^
error: 21: name 'input' is reserved
            c += input.eval(p + float2(x, y));
                 ^^^^^
error: 20: loop index initializer must be a constant expression
        for (float y = -blur_radius; y <= blur_radius; y += 1.0) {
             ^^^^^^^^^^^^^^^^^^^^^^
error: 19: loop index initializer must be a constant expression
    for (float x = -blur_radius; x <= blur_radius; x += 1.0) {
         ^^^^^^^^^^^^^^^^^^^^^^
4 errors

Release Notes:

Milestone 128
=============
SkSL now properly reports an error if user code includes various GLSL reserved keywords. Previously, Skia would correctly reject keywords that were included in “The OpenGL ES Shading Language, Version 1.00,” but did not detect reserved keywords added in more modern GLSL versions. Instead, Skia would allow such code to compile during the construction of a runtime effect, but actually rendering the effect using a modern version of OpenGL would silently fail (or assert) due to the presence of the reserved name in the the code.

Examples of reserved names which SkSL will now reject include dmat3x3, atomic_uint, isampler2D, or imageCubeArray.

For a more thorough list of reserved keywords, see the “3.6 Keywords” section of the OpenGL Shading Language documentation.